package com.appschef.trick;

public class StaticValues {

    public static int[] stickerList = {R.drawable.emoji1, R.drawable.emoji2, R.drawable.emoji3, R.drawable.emoji4, R.drawable.emoji5, R.drawable.emoji6,
            R.drawable.emoji7, R.drawable.emoji8, R.drawable.emoji9, R.drawable.emoji10};
    public static int[] hairStyle = {R.drawable.classic_1,R.drawable.classic_2,R.drawable.classic_3,R.drawable.classic_4,R.drawable.classic_5,R.drawable.classic_6,R.drawable.classic_7,R.drawable.classic_8,R.drawable.classic_9,R.drawable.classic_10,R.drawable.mustache_1,R.drawable.mustache_2,R.drawable.mustache_3,R.drawable.mustache_4,R.drawable.mustache_5,R.drawable.mustache_6,R.drawable.mustache_7,R.drawable.mustache_8,R.drawable.mustache_9,R.drawable.mustache_10,R.drawable.beard_1, R.drawable.beard_2, R.drawable.beard_3, R.drawable.beard_4, R.drawable.beard_5, R.drawable.beard_6, R.drawable.beard_7
            , R.drawable.beard_8, R.drawable.beard_9, R.drawable.beard_10,R.drawable.eyebrow_1,R.drawable.eyebrow_2,R.drawable.eyebrow_3,R.drawable.eyebrow_4,R.drawable.eyebrow_5
            ,R.drawable.eyebrow_6,R.drawable.eyebrow_7,R.drawable.eyebrow_8,R.drawable.eyebrow_9,R.drawable.eyebrow_10};
public static int[] acc={R.drawable.eye_1,R.drawable.eye_2,R.drawable.eye_3,R.drawable.eye_4,R.drawable.eye_5,R.drawable.eye_6,R.drawable.eye_7,R.drawable.eye_8,R.drawable.eye_9,R.drawable.eye_10,R.drawable.stole_1,R.drawable.stole_2,R.drawable.stole_3,R.drawable.stole_4,R.drawable.stole_5,R.drawable.stole_6,R.drawable.stole_7,R.drawable.stole_8,R.drawable.stole_9,
        R.drawable.stole_10,R.drawable.sunglasses_1,R.drawable.sunglasses_2,R.drawable.sunglasses_3,R.drawable.sunglasses_4,R.drawable.sunglasses_5,R.drawable.sunglasses_6,R.drawable.sunglasses_7,R.drawable.sunglasses_8,R.drawable.sunglasses_9,R.drawable.sunglasses_10,R.drawable.chain_1,R.drawable.chain_2,R.drawable.chain_3,R.drawable.chain_4,R.drawable.chain_5,R.drawable.chain_6,R.drawable.chain_7,R.drawable.chain_8,R.drawable.chain_9,R.drawable.chain_10,R.drawable.tie_1,R.drawable.tie_2,R.drawable.tie_3,R.drawable.tie_4,R.drawable.tie_5,R.drawable.tie_6,R.drawable.tie_7,R.drawable.tie_8,
        R.drawable.tie_9,R.drawable.tie_10,R.drawable.cap_1,R.drawable.cap_2,R.drawable.cap_3,R.drawable.cap_4,R.drawable.cap_5,R.drawable.cap_6,R.drawable.cap_7,R.drawable.cap_8,R.drawable.cap_9,R.drawable.cap_10 };
public static int[] all={R.drawable.emoji1, R.drawable.emoji2, R.drawable.emoji3, R.drawable.emoji4, R.drawable.emoji5, R.drawable.emoji6,
        R.drawable.emoji7, R.drawable.emoji8, R.drawable.emoji9, R.drawable.emoji10,R.drawable.classic_1,R.drawable.classic_2,R.drawable.classic_3,R.drawable.classic_4,R.drawable.classic_5,R.drawable.classic_6,R.drawable.classic_7,R.drawable.classic_8,R.drawable.classic_9,R.drawable.classic_10,R.drawable.mustache_1,R.drawable.mustache_2,R.drawable.mustache_3,R.drawable.mustache_4,R.drawable.mustache_5,R.drawable.mustache_6,R.drawable.mustache_7,R.drawable.mustache_8,R.drawable.mustache_9,R.drawable.mustache_10,R.drawable.beard_1, R.drawable.beard_2, R.drawable.beard_3, R.drawable.beard_4, R.drawable.beard_5, R.drawable.beard_6, R.drawable.beard_7
        , R.drawable.beard_8, R.drawable.beard_9, R.drawable.beard_10,R.drawable.eyebrow_1,R.drawable.eyebrow_2,R.drawable.eyebrow_3,R.drawable.eyebrow_4,R.drawable.eyebrow_5
        ,R.drawable.eyebrow_6,R.drawable.eyebrow_7,R.drawable.eyebrow_8,R.drawable.eyebrow_9,R.drawable.eyebrow_10,R.drawable.eye_1,R.drawable.eye_2,R.drawable.eye_3,R.drawable.eye_4,R.drawable.eye_5,R.drawable.eye_6,R.drawable.eye_7,R.drawable.eye_8,R.drawable.eye_9,R.drawable.eye_10,R.drawable.stole_1,R.drawable.stole_2,R.drawable.stole_3,R.drawable.stole_4,R.drawable.stole_5,R.drawable.stole_6,R.drawable.stole_7,R.drawable.stole_8,R.drawable.stole_9,
        R.drawable.stole_10,R.drawable.sunglasses_1,R.drawable.sunglasses_2,R.drawable.sunglasses_3,R.drawable.sunglasses_4,R.drawable.sunglasses_5,R.drawable.sunglasses_6,R.drawable.sunglasses_7,R.drawable.sunglasses_8,R.drawable.sunglasses_9,R.drawable.sunglasses_10,R.drawable.chain_1,R.drawable.chain_2,R.drawable.chain_3,R.drawable.chain_4,R.drawable.chain_5,R.drawable.chain_6,R.drawable.chain_7,R.drawable.chain_8,R.drawable.chain_9,R.drawable.chain_10,R.drawable.tie_1,R.drawable.tie_2,R.drawable.tie_3,R.drawable.tie_4,R.drawable.tie_5,R.drawable.tie_6,R.drawable.tie_7,R.drawable.tie_8,
        R.drawable.tie_9,R.drawable.tie_10,R.drawable.cap_1,R.drawable.cap_2,R.drawable.cap_3,R.drawable.cap_4,R.drawable.cap_5,R.drawable.cap_6,R.drawable.cap_7,R.drawable.cap_8,R.drawable.cap_9,R.drawable.cap_10
};
}
